## Model Training Process 
    1. Generate Linear NN Model_ linear = nn.Linear(X, Y)
    2. Define Loss function, Optimiser in advance
    3. Prediction _ pred = linear(X)
    4. Loss function
    5. Backward Propagation()
    6. Training_ optimizer.step()

### Torch Configuration

In [18]:
import torch     # Pythorch framework ... called torch
import torchvision   # Library used in Image Processing (Visiong)in torch
import torch.nn as nn   # For Neural Network 
import numpy as np  
import torchvision.transforms as transforms   # For Data Augentation 

In [42]:
X = torch.Tensor(2,3)
# Same as =np.array([])
# Creating (2,3) shape of dataset using torch
# Dataset is initialised randomly
# Manually set the dataset like X=torch.Tensor([[1,2,3], [4,5,6]]), target = torch.tensor([3.0, 4.0]) if not Random

print(X)
print(X.size())

tensor([[8.4490e-39, 1.0102e-38, 9.0919e-39],
        [1.0102e-38, 8.9082e-39, 8.4489e-39]])
torch.Size([2, 3])


In [43]:
X=torch.Tensor([[1,2,3], [4,5,6]])
print(X)
print(X.size())

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [45]:
x = torch.tensor(data =[2.0,3.0], requires_grad=True)   
# requires_grad=True  is to set value of the gradient (slope)
# If it is set to False, can't do back propagaction (cuz don't have gradient to differentiate)

target = torch.tensor([3.0, 4.0])  

y=x**2

pred = 2*x + 3    # Predicted values
pred

tensor([7., 9.], grad_fn=<AddBackward0>)

In [46]:
loss = torch.sum(torch.abs(pred-target))    #(11-3)+(21-4)= 25  or (7-3)+(9-4)=9
print("loss", loss)

# Calculate Loss using Predicted values and target

loss tensor(9., grad_fn=<SumBackward0>)


In [21]:
loss.backward()   # Partial derivate goes on based on the loss value
print(x.grad)     # Output: Differentiated gradients

tensor([ 8., 12.])


## Generating NeuralNet Using Tensor

In [55]:
# Making Hypothes  ex)2x+3 
# requires_grad=True  for deffierential

x = torch.tensor(1., requires_grad = True)
w = torch.tensor(2., requires_grad = True)
b = torch.tensor(3., requires_grad = True)

print(x)
print(w)
print(b)

tensor(1., requires_grad=True)
tensor(2., requires_grad=True)
tensor(3., requires_grad=True)


In [57]:
y = w*x +b   
# Making Linear Function using x, w, b created above

y.backward()   
print(x.grad)
print(w.grad)
print(b.grad)

# .grad shows the result of the .backward() = differential

tensor(2.)
tensor(1.)
tensor(1.)


## Generating Two-Dimensional Neural Network

In [107]:
x= torch.randn(10,3)  
# Creating two dimensional dataset for the input

y=torch.randn(10,2)    
# Creating two dimensional dataset for the target
# randn() randomly selects numbers that follows Normal Distribution 

print(x)
print(y)

linear = nn.Linear(3,2)     
# Creating linear cliassifier (=linear)
# Input is 10 * 3 and Output is 10 * 2  >>>  Neural Network between the input and the output must be 3 * 2 

# In the FIRST run, RANDOMLY created Weights and Bias in Neural Network
print('w: ', linear.weight)   
# Checking Weights 
# Should be (3,2) shape but with no reason the output is trasposed to (2,3)

print('b: ', linear.bias)     
# Should be (10,2) because these will be added to y values which has the shape of (10,2) 
# But bias is all THE SAME for all the outputs (predictions)  so showing ONLY ONE  (1,2) the rest are skipped

tensor([[ 0.8540, -0.4819, -1.1634],
        [ 0.6633, -1.7154,  0.0080],
        [ 1.4841, -1.2872,  0.9404],
        [-1.7820, -0.3503, -0.8884],
        [-0.0420,  0.8181, -0.3515],
        [-2.1385, -1.0630, -0.9695],
        [-0.9215,  1.2832, -1.8755],
        [ 0.1687, -0.5799, -1.1411],
        [-2.5008,  0.0484,  1.0711],
        [-0.6472,  1.0035,  0.9775]])
tensor([[-0.9164,  0.3917],
        [-0.5226, -1.0022],
        [ 0.5995,  0.0933],
        [-1.0351,  0.8484],
        [ 0.8683,  0.4521],
        [ 1.4030, -1.2594],
        [-0.0867, -0.0369],
        [ 0.9726,  0.4877],
        [-0.3979, -0.8892],
        [ 0.6025, -1.0498]])
w:  Parameter containing:
tensor([[-0.0501, -0.1610,  0.1946],
        [-0.2623,  0.5052, -0.1571]], requires_grad=True)
b:  Parameter containing:
tensor([ 0.4628, -0.2250], requires_grad=True)


## Create Neural Network >> Predict >> Loss value >> Loss Function >> Backward Propagation

In [108]:
print(linear.parameters())
# .parameters() contains the subjects that are being trained (Weights and Bias)

<generator object Module.parameters at 0x000002D418AB34A0>


In [109]:
# Loss function(mse, cross entropy, ...) and optimiser(adam, sgd, rmsprop ...) 
# Should be defined in the beginning and CALLit when in use

loss_function = nn.MSELoss()   
# Defining Loss Function 

optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)   
# Defining Optimiser
# Designating the Learning Rate
# linear.parameters() has W and b 

pred = linear(x)
loss = loss_function(pred , y)
print('loss... before step back-propagation : ', loss.item())
# .item() : Chaning numpy to tenrsor

loss... before step back-propagation :  0.9029954671859741


In [116]:
loss.backward()
# Training hasn't begun only going through backpropagation (partial derivative)
# Finding how much Weights and Bias should change 

print('dL/dw : ', linear.weight.grad)
print('dL/db : ', linear.bias.grad)

dL/dw :  tensor([[-0.3379, -0.5209,  0.0847],
        [-1.8608,  0.9451,  0.1630]])
dL/db :  tensor([0.6109, 0.0626])


In [117]:
optimizer.step()   
# Training begins based on the backpropagation results
# Reapeating this == Training

In [118]:
pred = linear(x)
loss = loss_function(pred, y)

print('loss... after step back-propagation : ', loss.item())
# Loss value after the optimising using back propagation

loss... after step back-propagation :  0.8519375920295715


## Model Training Process 
    1. Generate Linear NN Model_ linear = nn.Linear(X, Y)
    2. Define Loss function, Optimiser in advance
    3. Prediction _ pred = linear(X)
    4. Loss function
    5. Backward Propagation()
    6. Training_ optimizer.step()